
export const MAJOR_ARCANA = [
  { number: '0', name: 'The Fool' },
  { number: 'I', name: 'The Magician' },
  { number: 'II', name: 'The High Priestess' },
  { number: 'III', name: 'The Empress' },
  { number: 'IV', name: 'The Emperor' },
  { number: 'V', name: 'The Hierophant' },
  { number: 'VI', name: 'The Lovers' },
  { number: 'VII', name: 'The Chariot' },
  { number: 'VIII', name: 'Strength' },
  { number: 'IX', name: 'The Hermit' },
  { number: 'X', name: 'Wheel of Fortune' },
  { number: 'XI', name: 'Justice' },
  { number: 'XII', name: 'The Hanged Man' },
  { number: 'XIII', name: 'Death' },
  { number: 'XIV', name: 'Temperance' },
  { number: 'XV', name: 'The Devil' },
  { number: 'XVI', name: 'The Tower' },
  { number: 'XVII', name: 'The Star' },
  { number: 'XVIII', name: 'The Moon' },
  { number: 'XIX', name: 'The Sun' },
  { number: 'XX', name: 'Judgement' },
  { number: 'XXI', name: 'The World' },
];
