import React, { createContext, useState, useCallback } from 'react';

const en = {
  "logout": "Logout",
  "welcomeToPath": "Welcome to Your Path of Discovery",
  "chooseService": "Choose a service below to begin your journey into the mystical arts and unlock the wisdom within.",
  "numerology": "Numerology",
  "numerologyDesc": "Uncover the secrets hidden in your name and birth date.",
  "astrology": "Astrology",
  "astrologyDesc": "Explore your destiny written in the stars and planets.",
  "tarot": "Tarot",
  "tarotDesc": "Draw a card and gain insight into your past, present, and future.",
  "palmistry": "Palmistry",
  "palmistryDesc": "Read the lines on your hand to understand your character and future.",
  "faceReading": "Face Reading",
  "faceReadingDesc": "Discover what your facial features reveal about your personality.",
  "personalGuidance": "Personal Guidance",
  "personalGuidanceDesc": "Get personalized remedies and guidance for your life challenges.",
  "backToHome": "Back to Home",
  "backToDashboard": "Back to Dashboard",
  "aiPalmReading": "AI Palmistry Reading",
  "uploadPalmPrompt": "Upload a clear photo of your palm to receive an instant, AI-powered palmistry reading.",
  "uploadInstruction": "Click to upload or capture a photo",
  "getYourReading": "Get My Reading",
  "analyzing": "Analyzing...",
  "yourReading": "Your Reading:",
  "readingPlaceholder": "Your palm reading summary will appear here.",
  "readMore": "Read More (Payment Required)",
  "downloadPDF": "Download PDF",
  "emailReport": "Email Report",
  "paymentSuccessful": "Payment Successful! Access your full report.",
  "aiFaceReading": "AI Face Reading",
  "uploadFacePrompt": "Upload a clear photo of your face to receive an instant, AI-powered face reading.",
  "faceReadingPlaceholder": "Your face reading summary will appear here.",
  "numerologyReading": "Numerology Reading",
  "astrologyReading": "Astrology Reading",
  "enterDetailsPrompt": "Enter your details below to generate your personalized {featureName} summary.",
  "fullName": "Full Name",
  "dob": "Date of Birth",
  "pob": "Place of Birth",
  "tob": "Time of Birth",
  "pobOptional": "Place of Birth (Optional for Numerology)",
  "tobOptional": "Time of Birth (Optional for Numerology)",
  "getMy": "Get My {featureName} Reading",
  "generating": "Generating...",
  "yourSummary": "Your {featureName} Summary",
  "tarotReading": "Tarot Reading",
  "tarotPrompt": "Select a card from the Major Arcana to reveal its mystical meaning for you.",
  "glyphCircle": "Glyph Circle",
  "enterCircle": "Enter the circle of wisdom.",
  "username": "Username",
  "password": "Password",
  "login": "Login",
  "orContinueWith": "Or continue with",
  "signInGoogle": "Sign in with Google",
  "signInPhone": "Sign in with Phone Number",
  "noAccount": "Don't have an account?",
  "createOne": "Create one",
  "createAccount": "Create Your Account",
  "email": "Email",
  "confirmPassword": "Confirm Password",
  "backToLogin": "Back to Login",
  "signIn": "Sign in",
  "toContinue": "to continue to Glyph Circle",
  "selectAccount": "Choose an account",
  "useAnotherAccount": "Use another account",
  "enterOTP": "Enter OTP",
  "otpPrompt": "A 6-digit code has been sent to your phone.",
  "otpDemo": "For demo, use OTP: 123456",
  "verify": "Verify",
  "back": "Back",
  "unlockReport": "Unlock Full Report",
  "paymentPrompt": "For a one-time payment of {price}, gain full access to your detailed reading.",
  "billingInfo": "Billing Information",
  "address": "Address",
  "city": "City",
  "zip": "ZIP / Postal Code",
  "country": "Country",
  "proceedToPayment": "Proceed to Payment",
  "payTo": "You are paying:",
  "creditCard": "Credit or Debit Card",
  "paypal": "PayPal",
  "paypalNote": "Payments will be sent to {email}",
  "payNow": "Pay Now",
  "paymentSuccessTitle": "Payment Successful!",
  "paymentSuccessMsg": "Your full report is now unlocked.",
  "adminDashboard": "Admin Dashboard",
  "runTheApp": "Run the App",
  "runTheAppDesc": "Proceed to the main user-facing application.",
  "showTheConfig": "Show the Config",
  "showTheConfigDesc": "Access the admin panel to manage the application.",
  "adminConfigTitle": "Admin Configuration",
  "adminConfigDesc": "Select a database table to view and manage its entries. Changes made here are now saved for your browser session.",
  "editing": "Editing: {tableName}",
  "toggleStatus": "Toggle Status",
  "createNewEntry": "Create New Entry",
  "actions": "Actions",
  "noEntries": "No entries in this table.",
  "createEntryIn": "Create New Entry in {tableName}",
  "cancel": "Cancel",
  "create": "Create",
  "featureComingSoon": "{featureName} is coming soon.",
  "stayTuned": "Stay tuned for mystical insights!",
  "goBackHome": "Go Back to Home"
};

const hi = {
  "logout": "लॉग आउट",
  "welcomeToPath": "खोज की अपनी राह में आपका स्वागत है",
  "chooseService": "रहस्यमय कलाओं में अपनी यात्रा शुरू करने और भीतर के ज्ञान को अनलॉक करने के लिए नीचे दी गई सेवा चुनें।",
  "numerology": "अंक ज्योतिष",
  "numerologyDesc": "अपने नाम और जन्म तिथि में छिपे रहस्यों को उजागर करें।",
  "astrology": "ज्योतिष",
  "astrologyDesc": "तारों और ग्रहों में लिखे अपने भाग्य का अन्वेषण करें।",
  "tarot": "टैरो",
  "tarotDesc": "एक कार्ड बनाएं और अपने अतीत, वर्तमान और भविष्य के बारे में जानकारी प्राप्त करें।",
  "palmistry": "हस्तरेखा शास्त्र",
  "palmistryDesc": "अपने चरित्र और भविष्य को समझने के लिए अपने हाथ की रेखाओं को पढ़ें।",
  "faceReading": "चेहरा पढ़ना",
  "faceReadingDesc": "पता लगाएं कि आपके चेहरे की विशेषताएं आपके व्यक्तित्व के बारे में क्या बताती हैं।",
  "personalGuidance": "व्यक्तिगत मार्गदर्शन",
  "personalGuidanceDesc": "अपने जीवन की चुनौतियों के लिए व्यक्तिगत उपचार और मार्गदर्शन प्राप्त करें।",
  "backToHome": "होम पर वापस जाएं",
  "backToDashboard": "डैशबोर्ड पर वापस जाएं",
  "aiPalmReading": "एआई हस्तरेखा पढ़ना",
  "uploadPalmPrompt": "एक त्वरित, एआई-संचालित हस्तरेखा पढ़ने के लिए अपनी हथेली की एक स्पष्ट तस्वीर अपलोड करें।",
  "uploadInstruction": "फोटो अपलोड करने या कैप्चर करने के लिए क्लिक करें",
  "getYourReading": "मेरी रीडिंग प्राप्त करें",
  "analyzing": "विश्लेषण हो रहा है...",
  "yourReading": "आपकी रीडिंग:",
  "readingPlaceholder": "आपकी हथेली पढ़ने का सारांश यहाँ दिखाई देगा।",
  "readMore": "और पढ़ें (भुगतान आवश्यक)",
  "downloadPDF": "पीडीएफ डाउनलोड करें",
  "emailReport": "ईमेल रिपोर्ट",
  "paymentSuccessful": "भुगतान सफल! अपनी पूरी रिपोर्ट तक पहुँचें।",
  "aiFaceReading": "एआई चेहरा पढ़ना",
  "uploadFacePrompt": "एक त्वरित, एआई-संचालित चेहरा पढ़ने के लिए अपने चेहरे की एक स्पष्ट तस्वीर अपलोड करें।",
  "faceReadingPlaceholder": "आपके चेहरे को पढ़ने का सारांश यहाँ दिखाई देगा।",
  "numerologyReading": "अंक ज्योतिष पढ़ना",
  "astrologyReading": "ज्योतिष पढ़ना",
  "enterDetailsPrompt": "अपना व्यक्तिगत {featureName} सारांश उत्पन्न करने के लिए नीचे अपना विवरण दर्ज करें।",
  "fullName": "पूरा नाम",
  "dob": "जन्म की तारीख",
  "pob": "जन्म स्थान",
  "tob": "जन्म का समय",
  "pobOptional": "जन्म स्थान (अंक ज्योतिष के लिए वैकल्पिक)",
  "tobOptional": "जन्म का समय (अंक ज्योतिष के लिए वैकल्पिक)",
  "getMy": "मेरा {featureName} रीडिंग प्राप्त करें",
  "generating": "उत्पन्न हो रहा है...",
  "yourSummary": "आपका {featureName} सारांश",
  "tarotReading": "टैरो पढ़ना",
  "tarotPrompt": "अपने लिए इसका रहस्यमय अर्थ प्रकट करने के लिए मेजर आर्काना से एक कार्ड चुनें।",
  "glyphCircle": "ग्लिफ़ सर्कल",
  "enterCircle": "ज्ञान के घेरे में प्रवेश करें।",
  "username": "उपयोगकर्ता नाम",
  "password": "पासवर्ड",
  "login": "लॉग इन करें",
  "orContinueWith": "या इसके साथ जारी रखें",
  "signInGoogle": "Google के साथ साइन इन करें",
  "signInPhone": "फोन नंबर से साइन इन करें",
  "noAccount": "कोई खाता नहीं है?",
  "createOne": "एक बनाएं",
  "createAccount": "अपना खाता बनाएं",
  "email": "ईमेल",
  "confirmPassword": "पासवर्ड की पुष्टि करें",
  "backToLogin": "लॉगिन पर वापस जाएं",
  "signIn": "साइन इन करें",
  "toContinue": "ग्लाइफ सर्कल पर जारी रखने के लिए",
  "selectAccount": "एक खाता चुनें",
  "useAnotherAccount": "दूसरा खाता उपयोग करें",
  "enterOTP": "OTP दर्ज करें",
  "otpPrompt": "आपके फ़ोन पर 6 अंकों का कोड भेजा गया है।",
  "otpDemo": "डेमो के लिए, OTP का उपयोग करें: 123456",
  "verify": "सत्यापित करें",
  "back": "वापस",
  "unlockReport": "पूरी रिपोर्ट अनलॉक करें",
  "paymentPrompt": "{price} के एकमुश्त भुगतान के लिए, अपनी विस्तृत रीडिंग तक पूरी पहुँच प्राप्त करें।",
  "billingInfo": "बिलिंग जानकारी",
  "address": "पता",
  "city": "शहर",
  "zip": "ज़िप / पोस्टल कोड",
  "country": "देश",
  "proceedToPayment": "भुगतान के लिए आगे बढ़ें",
  "payTo": "आप भुगतान कर रहे हैं:",
  "creditCard": "क्रेडिट या डेबिट कार्ड",
  "paypal": "पेपैल",
  "paypalNote": "भुगतान {email} पर भेजा जाएगा",
  "payNow": "अभी भुगतान करें",
  "paymentSuccessTitle": "भुगतान सफल!",
  "paymentSuccessMsg": "आपकी पूरी रिपोर्ट अब अनलॉक हो गई है।",
  "adminDashboard": "एडमिन डैशबोर्ड",
  "runTheApp": "ऐप चलाएं",
  "runTheAppDesc": "मुख्य उपयोगकर्ता-सामना एप्लिकेशन पर आगे बढ़ें।",
  "showTheConfig": "कॉन्फ़िग दिखाएं",
  "showTheConfigDesc": "एप्लिकेशन को प्रबंधित करने के लिए एडमिन पैनल तक पहुंचें।",
  "adminConfigTitle": "एडमिन कॉन्फ़िगरेशन",
  "adminConfigDesc": "डेटाबेस तालिका का चयन करें और उसकी प्रविष्टियों को प्रबंधित करें। यहां किए गए परिवर्तन आपके ब्राउज़र सत्र के लिए सहेजे जाते हैं।",
  "editing": "संपादन: {tableName}",
  "toggleStatus": "स्थिति टॉगल करें",
  "createNewEntry": "नई प्रविष्टि बनाएं",
  "actions": "कार्रवाइयां",
  "noEntries": "इस तालिका में कोई प्रविष्टि नहीं है।",
  "createEntryIn": "{tableName} में नई प्रविष्टि बनाएं",
  "cancel": "रद्द करें",
  "create": "बनाएं",
  "featureComingSoon": "{featureName} जल्द ही आ रहा है।",
  "stayTuned": "रहस्यमय अंतर्दृष्टि के लिए बने रहें!",
  "goBackHome": "होम पर वापस जाएं"
};

const fr = {
  "logout": "Déconnexion",
  "welcomeToPath": "Bienvenue sur Votre Chemin de Découverte",
  "chooseService": "Choisissez un service ci-dessous pour commencer votre voyage dans les arts mystiques et libérer la sagesse qui est en vous.",
  "numerology": "Numérologie",
  "numerologyDesc": "Découvrez les secrets cachés dans votre nom et votre date de naissance.",
  "astrology": "Astrologie",
  "astrologyDesc": "Explorez votre destin écrit dans les étoiles et les planètes.",
  "tarot": "Tarot",
  "tarotDesc": "Tirez une carte et obtenez un aperçu de votre passé, présent et futur.",
  "palmistry": "Chiromancie",
  "palmistryDesc": "Lisez les lignes de votre main pour comprendre votre caractère et votre avenir.",
  "faceReading": "Lecture du visage",
  "faceReadingDesc": "Découvrez ce que les traits de votre visage révèlent sur votre personnalité.",
  "personalGuidance": "Guidance Personnelle",
  "personalGuidanceDesc": "Obtenez des remèdes et des conseils personnalisés pour vos défis de vie.",
  "backToHome": "Retour à l'accueil",
  "backToDashboard": "Retour au tableau de bord",
  "aiPalmReading": "Lecture de Chiromancie par IA",
  "uploadPalmPrompt": "Téléchargez une photo claire de votre paume pour recevoir une lecture de chiromancie instantanée et alimentée par l'IA.",
  "uploadInstruction": "Cliquez pour télécharger ou capturer une photo",
  "getYourReading": "Obtenir ma lecture",
  "analyzing": "Analyse en cours...",
  "yourReading": "Votre Lecture :",
  "readingPlaceholder": "Votre résumé de lecture de paume apparaîtra ici.",
  "readMore": "En savoir plus (Paiement requis)",
  "downloadPDF": "Télécharger le PDF",
  "emailReport": "Envoyer le rapport par e-mail",
  "paymentSuccessful": "Paiement réussi ! Accédez à votre rapport complet.",
  "aiFaceReading": "Lecture du Visage par IA",
  "uploadFacePrompt": "Téléchargez une photo claire de votre visage pour recevoir une lecture de visage instantanée et alimentée par l'IA.",
  "faceReadingPlaceholder": "Votre résumé de lecture de visage apparaîtra ici.",
  "numerologyReading": "Lecture de Numérologie",
  "astrologyReading": "Lecture d'Astrologie",
  "enterDetailsPrompt": "Entrez vos détails ci-dessous pour générer votre résumé personnalisé de {featureName}.",
  "fullName": "Nom complet",
  "dob": "Date de naissance",
  "pob": "Lieu de naissance",
  "tob": "Heure de naissance",
  "pobOptional": "Lieu de naissance (Facultatif pour la numérologie)",
  "tobOptional": "Heure de naissance (Facultatif pour la numérologie)",
  "getMy": "Obtenir ma lecture de {featureName}",
  "generating": "Génération en cours...",
  "yourSummary": "Votre résumé de {featureName}",
  "tarotReading": "Lecture de Tarot",
  "tarotPrompt": "Sélectionnez une carte des Arcanes Majeurs pour révéler sa signification mystique pour vous.",
  "glyphCircle": "Cercle des Glyphes",
  "enterCircle": "Entrez dans le cercle de la sagesse.",
  "username": "Nom d'utilisateur",
  "password": "Mot de passe",
  "login": "Connexion",
  "orContinueWith": "Ou continuer avec",
  "signInGoogle": "Se connecter avec Google",
  "signInPhone": "Se connecter avec un numéro de téléphone",
  "noAccount": "Vous n'avez pas de compte ?",
  "createOne": "En créer un",
  "createAccount": "Créez votre compte",
  "email": "E-mail",
  "confirmPassword": "Confirmez le mot de passe",
  "backToLogin": "Retour à la connexion",
  "signIn": "Se connecter",
  "toContinue": "pour continuer vers le Cercle des Glyphes",
  "selectAccount": "Choisissez un compte",
  "useAnotherAccount": "Utiliser un autre compte",
  "enterOTP": "Entrez le code OTP",
  "otpPrompt": "Un code à 6 chiffres a été envoyé sur votre téléphone.",
  "otpDemo": "Pour la démo, utilisez le code OTP : 123456",
  "verify": "Vérifier",
  "back": "Retour",
  "unlockReport": "Débloquer le rapport complet",
  "paymentPrompt": "Pour un paiement unique de {price}, accédez entièrement à votre lecture détaillée.",
  "billingInfo": "Informations de facturation",
  "address": "Adresse",
  "city": "Ville",
  "zip": "Code postal",
  "country": "Pays",
  "proceedToPayment": "Procéder au paiement",
  "payTo": "Vous payez à :",
  "creditCard": "Carte de crédit ou de débit",
  "paypal": "PayPal",
  "paypalNote": "Les paiements seront envoyés à {email}",
  "payNow": "Payer maintenant",
  "paymentSuccessTitle": "Paiement réussi !",
  "paymentSuccessMsg": "Votre rapport complet est maintenant débloqué.",
  "adminDashboard": "Tableau de bord administrateur",
  "runTheApp": "Lancer l'application",
  "runTheAppDesc": "Accéder à l'application principale destinée aux utilisateurs.",
  "showTheConfig": "Afficher la configuration",
  "showTheConfigDesc": "Accéder au panneau d'administration pour gérer l'application.",
  "adminConfigTitle": "Configuration administrateur",
  "adminConfigDesc": "Sélectionnez une table de base de données pour afficher et gérer ses entrées. Les modifications apportées ici sont maintenant enregistrées pour votre session de navigateur.",
  "editing": "Édition de : {tableName}",
  "toggleStatus": "Changer le statut",
  "createNewEntry": "Créer une nouvelle entrée",
  "actions": "Actions",
  "noEntries": "Aucune entrée dans cette table.",
  "createEntryIn": "Créer une nouvelle entrée dans {tableName}",
  "cancel": "Annuler",
  "create": "Créer",
  "featureComingSoon": "{featureName} arrive bientôt.",
  "stayTuned": "Restez à l'écoute pour des aperçus mystiques !",
  "goBackHome": "Retour à l'accueil"
};

const es = {
  "logout": "Cerrar sesión",
  "welcomeToPath": "Bienvenido a Tu Camino de Descubrimiento",
  "chooseService": "Elige un servicio a continuación para comenzar tu viaje en las artes místicas y desbloquear la sabiduría interior.",
  "numerology": "Numerología",
  "numerologyDesc": "Descubre los secretos ocultos en tu nombre y fecha de nacimiento.",
  "astrology": "Astrología",
  "astrologyDesc": "Explora tu destino escrito en las estrellas y los planetas.",
  "tarot": "Tarot",
  "tarotDesc": "Saca una carta y obtén una visión de tu pasado, presente y futuro.",
  "palmistry": "Quiromancia",
  "palmistryDesc": "Lee las líneas de tu mano para entender tu carácter y futuro.",
  "faceReading": "Lectura de Rostro",
  "faceReadingDesc": "Descubre lo que tus rasgos faciales revelan sobre tu personalidad.",
  "personalGuidance": "Guía Personal",
  "personalGuidanceDesc": "Obtén remedios y orientación personalizados para los desafíos de tu vida.",
  "backToHome": "Volver al Inicio",
  "backToDashboard": "Volver al Panel",
  "aiPalmReading": "Lectura de Quiromancia con IA",
  "uploadPalmPrompt": "Sube una foto clara de tu palma para recibir una lectura de quiromancia instantánea impulsada por IA.",
  "uploadInstruction": "Haz clic para subir o capturar una foto",
  "getYourReading": "Obtener mi Lectura",
  "analyzing": "Analizando...",
  "yourReading": "Tu Lectura:",
  "readingPlaceholder": "El resumen de la lectura de tu palma aparecerá aquí.",
  "readMore": "Leer Más (Pago Requerido)",
  "downloadPDF": "Descargar PDF",
  "emailReport": "Enviar Informe por Correo",
  "paymentSuccessful": "¡Pago Exitoso! Accede a tu informe completo.",
  "aiFaceReading": "Lectura de Rostro con IA",
  "uploadFacePrompt": "Sube una foto clara de tu rostro para recibir una lectura de rostro instantánea impulsada por IA.",
  "faceReadingPlaceholder": "El resumen de la lectura de tu rostro aparecerá aquí.",
  "numerologyReading": "Lectura de Numerología",
  "astrologyReading": "Lectura de Astrología",
  "enterDetailsPrompt": "Ingresa tus datos a continuación para generar tu resumen personalizado de {featureName}.",
  "fullName": "Nombre Completo",
  "dob": "Fecha de Nacimiento",
  "pob": "Lugar de Nacimiento",
  "tob": "Hora de Nacimiento",
  "pobOptional": "Lugar de Nacimiento (Opcional para Numerología)",
  "tobOptional": "Hora de Nacimiento (Opcional para Numerología)",
  "getMy": "Obtener mi Lectura de {featureName}",
  "generating": "Generando...",
  "yourSummary": "Tu Resumen de {featureName}",
  "tarotReading": "Lectura de Tarot",
  "tarotPrompt": "Selecciona una carta de los Arcanos Mayores para revelar su significado místico para ti.",
  "glyphCircle": "Círculo de Glifos",
  "enterCircle": "Entra en el círculo de la sabiduría.",
  "username": "Nombre de Usuario",
  "password": "Contraseña",
  "login": "Iniciar Sesión",
  "orContinueWith": "O continuar con",
  "signInGoogle": "Iniciar sesión con Google",
  "signInPhone": "Iniciar sesión con número de teléfono",
  "noAccount": "¿No tienes una cuenta?",
  "createOne": "Crear una",
  "createAccount": "Crea tu cuenta",
  "email": "Correo Electrónico",
  "confirmPassword": "Confirmar Contraseña",
  "backToLogin": "Volver al inicio de sesión",
  "signIn": "Iniciar sesión",
  "toContinue": "para continuar a Círculo de Glifos",
  "selectAccount": "Elige una cuenta",
  "useAnotherAccount": "Usar otra cuenta",
  "enterOTP": "Ingresar OTP",
  "otpPrompt": "Se ha enviado un código de 6 dígitos a tu teléfono.",
  "otpDemo": "Para la demostración, usa el OTP: 123456",
  "verify": "Verificar",
  "back": "Atrás",
  "unlockReport": "Desbloquear Informe Completo",
  "paymentPrompt": "Por un pago único de {price}, obtén acceso completo a tu lectura detallada.",
  "billingInfo": "Información de Facturación",
  "address": "Dirección",
  "city": "Ciudad",
  "zip": "Código Postal",
  "country": "País",
  "proceedToPayment": "Proceder al Pago",
  "payTo": "Estás pagando a:",
  "creditCard": "Tarjeta de Crédito o Débito",
  "paypal": "PayPal",
  "paypalNote": "Los pagos se enviarán a {email}",
  "payNow": "Pagar Ahora",
  "paymentSuccessTitle": "¡Pago Exitoso!",
  "paymentSuccessMsg": "Tu informe completo ya está desbloqueado.",
  "adminDashboard": "Panel de Administración",
  "runTheApp": "Ejecutar la Aplicación",
  "runTheAppDesc": "Proceder a la aplicación principal para el usuario.",
  "showTheConfig": "Mostrar la Configuración",
  "showTheConfigDesc": "Accede al panel de administración para gestionar la aplicación.",
  "adminConfigTitle": "Configuración de Administración",
  "adminConfigDesc": "Selecciona una tabla de la base de datos para ver y gestionar sus entradas. Los cambios realizados aquí se guardan para la sesión de tu navegador.",
  "editing": "Editando: {tableName}",
  "toggleStatus": "Cambiar Estado",
  "createNewEntry": "Crear Nueva Entrada",
  "actions": "Acciones",
  "noEntries": "No hay entradas en esta tabla.",
  "createEntryIn": "Crear Nueva Entrada en {tableName}",
  "cancel": "Cancelar",
  "create": "Crear",
  "featureComingSoon": "{featureName} estará disponible pronto.",
  "stayTuned": "¡Mantente atento a las revelaciones místicas!",
  "goBackHome": "Volver al Inicio"
};

const de = {
  "logout": "Abmelden",
  "welcomeToPath": "Willkommen auf Deinem Weg der Entdeckung",
  "chooseService": "Wähle unten einen Dienst, um deine Reise in die mystischen Künste zu beginnen und die Weisheit in dir freizuschalten.",
  "numerology": "Numerologie",
  "numerologyDesc": "Entdecke die Geheimnisse, die in deinem Namen und Geburtsdatum verborgen sind.",
  "astrology": "Astrologie",
  "astrologyDesc": "Erforsche dein Schicksal, das in den Sternen und Planeten geschrieben steht.",
  "tarot": "Tarot",
  "tarotDesc": "Ziehe eine Karte und erhalte Einblick in deine Vergangenheit, Gegenwart und Zukunft.",
  "palmistry": "Handlesekunst",
  "palmistryDesc": "Lies die Linien auf deiner Hand, um deinen Charakter und deine Zukunft zu verstehen.",
  "faceReading": "Gesichtslesen",
  "faceReadingDesc": "Entdecke, was deine Gesichtszüge über deine Persönlichkeit verraten.",
  "personalGuidance": "Persönliche Führung",
  "personalGuidanceDesc": "Erhalte personalisierte Heilmittel und Führung für deine Lebensherausforderungen.",
  "backToHome": "Zurück zur Startseite",
  "backToDashboard": "Zurück zum Dashboard",
  "aiPalmReading": "KI-Handlesen",
  "uploadPalmPrompt": "Lade ein klares Foto deiner Handfläche hoch, um eine sofortige, KI-gestützte Handlesung zu erhalten.",
  "uploadInstruction": "Klicke, um ein Foto hochzuladen oder aufzunehmen",
  "getYourReading": "Meine Lesung erhalten",
  "analyzing": "Analysiere...",
  "yourReading": "Deine Lesung:",
  "readingPlaceholder": "Deine Zusammenfassung der Handlesung wird hier erscheinen.",
  "readMore": "Mehr lesen (Zahlung erforderlich)",
  "downloadPDF": "PDF herunterladen",
  "emailReport": "Bericht per E-Mail senden",
  "paymentSuccessful": "Zahlung erfolgreich! Greife auf deinen vollständigen Bericht zu.",
  "aiFaceReading": "KI-Gesichtslesen",
  "uploadFacePrompt": "Lade ein klares Foto deines Gesichts hoch, um eine sofortige, KI-gestützte Gesichtslesung zu erhalten.",
  "faceReadingPlaceholder": "Deine Zusammenfassung der Gesichtslesung wird hier erscheinen.",
  "numerologyReading": "Numerologie-Lesung",
  "astrologyReading": "Astrologie-Lesung",
  "enterDetailsPrompt": "Gib unten deine Daten ein, um deine personalisierte {featureName}-Zusammenfassung zu erstellen.",
  "fullName": "Vollständiger Name",
  "dob": "Geburtsdatum",
  "pob": "Geburtsort",
  "tob": "Geburtszeit",
  "pobOptional": "Geburtsort (Optional für Numerologie)",
  "tobOptional": "Geburtszeit (Optional für Numerologie)",
  "getMy": "Meine {featureName}-Lesung erhalten",
  "generating": "Wird generiert...",
  "yourSummary": "Deine {featureName}-Zusammenfassung",
  "tarotReading": "Tarot-Lesung",
  "tarotPrompt": "Wähle eine Karte aus der Großen Arkana, um ihre mystische Bedeutung für dich zu enthüllen.",
  "glyphCircle": "Glyphenkreis",
  "enterCircle": "Tritt ein in den Kreis der Weisheit.",
  "username": "Benutzername",
  "password": "Passwort",
  "login": "Anmelden",
  "orContinueWith": "Oder fahre fort mit",
  "signInGoogle": "Mit Google anmelden",
  "signInPhone": "Mit Telefonnummer anmelden",
  "noAccount": "Kein Konto?",
  "createOne": "Erstelle eins",
  "createAccount": "Dein Konto erstellen",
  "email": "E-Mail",
  "confirmPassword": "Passwort bestätigen",
  "backToLogin": "Zurück zum Login",
  "signIn": "Anmelden",
  "toContinue": "um zum Glyphenkreis fortzufahren",
  "selectAccount": "Wähle ein Konto",
  "useAnotherAccount": "Ein anderes Konto verwenden",
  "enterOTP": "OTP eingeben",
  "otpPrompt": "Ein 6-stelliger Code wurde an dein Telefon gesendet.",
  "otpDemo": "Für die Demo, verwende OTP: 123456",
  "verify": "Verifizieren",
  "back": "Zurück",
  "unlockReport": "Vollständigen Bericht freischalten",
  "paymentPrompt": "Für eine einmalige Zahlung von {price}, erhalte vollen Zugriff auf deine detaillierte Lesung.",
  "billingInfo": "Rechnungsinformationen",
  "address": "Adresse",
  "city": "Stadt",
  "zip": "Postleitzahl",
  "country": "Land",
  "proceedToPayment": "Zur Zahlung übergehen",
  "payTo": "Du zahlst an:",
  "creditCard": "Kredit- oder Debitkarte",
  "paypal": "PayPal",
  "paypalNote": "Zahlungen werden an {email} gesendet",
  "payNow": "Jetzt bezahlen",
  "paymentSuccessTitle": "Zahlung erfolgreich!",
  "paymentSuccessMsg": "Dein vollständiger Bericht ist jetzt freigeschaltet.",
  "adminDashboard": "Admin-Dashboard",
  "runTheApp": "App ausführen",
  "runTheAppDesc": "Zur Hauptanwendung für Benutzer wechseln.",
  "showTheConfig": "Konfiguration anzeigen",
  "showTheConfigDesc": "Greife auf das Admin-Panel zu, um die Anwendung zu verwalten.",
  "adminConfigTitle": "Admin-Konfiguration",
  "adminConfigDesc": "Wähle eine Datenbanktabelle aus, um ihre Einträge anzuzeigen und zu verwalten. Änderungen werden für deine Browsersitzung gespeichert.",
  "editing": "Bearbeite: {tableName}",
  "toggleStatus": "Status umschalten",
  "createNewEntry": "Neuen Eintrag erstellen",
  "actions": "Aktionen",
  "noEntries": "Keine Einträge in dieser Tabelle.",
  "createEntryIn": "Neuen Eintrag in {tableName} erstellen",
  "cancel": "Abbrechen",
  "create": "Erstellen",
  "featureComingSoon": "{featureName} kommt bald.",
  "stayTuned": "Bleib dran für mystische Einblicke!",
  "goBackHome": "Zurück zur Startseite"
};

const ru = {
  "logout": "Выйти",
  "welcomeToPath": "Добро пожаловать на Ваш Путь Открытий",
  "chooseService": "Выберите услугу ниже, чтобы начать свое путешествие в мистические искусства и раскрыть мудрость внутри себя.",
  "numerology": "Нумерология",
  "numerologyDesc": "Раскройте тайны, скрытые в вашем имени и дате рождения.",
  "astrology": "Астрология",
  "astrologyDesc": "Исследуйте свою судьбу, написанную в звездах и планетах.",
  "tarot": "Таро",
  "tarotDesc": "Вытяните карту и получите представление о своем прошлом, настоящем и будущем.",
  "palmistry": "Хиромантия",
  "palmistryDesc": "Прочитайте линии на вашей руке, чтобы понять свой характер и будущее.",
  "faceReading": "Чтение по лицу",
  "faceReadingDesc": "Узнайте, что черты вашего лица говорят о вашей личности.",
  "personalGuidance": "Личное Руководство",
  "personalGuidanceDesc": "Получите персонализированные средства и руководство для ваших жизненных проблем.",
  "backToHome": "Вернуться на главную",
  "backToDashboard": "Вернуться в панель управления",
  "aiPalmReading": "Чтение по ладони с помощью ИИ",
  "uploadPalmPrompt": "Загрузите четкое фото вашей ладони, чтобы получить мгновенное чтение по ладони на основе ИИ.",
  "uploadInstruction": "Нажмите, чтобы загрузить или сделать фото",
  "getYourReading": "Получить мое чтение",
  "analyzing": "Анализ...",
  "yourReading": "Ваше Чтение:",
  "readingPlaceholder": "Ваше краткое изложение чтения по ладони появится здесь.",
  "readMore": "Читать далее (требуется оплата)",
  "downloadPDF": "Скачать PDF",
  "emailReport": "Отправить отчет по электронной почте",
  "paymentSuccessful": "Оплата прошла успешно! Получите доступ к полному отчету.",
  "aiFaceReading": "Чтение по лицу с помощью ИИ",
  "uploadFacePrompt": "Загрузите четкое фото вашего лица, чтобы получить мгновенное чтение по лицу на основе ИИ.",
  "faceReadingPlaceholder": "Ваше краткое изложение чтения по лицу появится здесь.",
  "numerologyReading": "Нумерологическое чтение",
  "astrologyReading": "Астрологическое чтение",
  "enterDetailsPrompt": "Введите ваши данные ниже, чтобы сгенерировать ваше персонализированное резюме по {featureName}.",
  "fullName": "Полное имя",
  "dob": "Дата рождения",
  "pob": "Место рождения",
  "tob": "Время рождения",
  "pobOptional": "Место рождения (необязательно для нумерологии)",
  "tobOptional": "Время рождения (необязательно для нумерологии)",
  "getMy": "Получить мое чтение по {featureName}",
  "generating": "Генерация...",
  "yourSummary": "Ваше резюме по {featureName}",
  "tarotReading": "Чтение Таро",
  "tarotPrompt": "Выберите карту из Старших Арканов, чтобы раскрыть ее мистическое значение для вас.",
  "glyphCircle": "Круг Глифов",
  "enterCircle": "Войдите в круг мудрости.",
  "username": "Имя пользователя",
  "password": "Пароль",
  "login": "Войти",
  "orContinueWith": "Или продолжить с",
  "signInGoogle": "Войти через Google",
  "signInPhone": "Войти по номеру телефона",
  "noAccount": "Нет аккаунта?",
  "createOne": "Создать",
  "createAccount": "Создать ваш аккаунт",
  "email": "Электронная почта",
  "confirmPassword": "Подтвердите пароль",
  "backToLogin": "Вернуться ко входу",
  "signIn": "Войти",
  "toContinue": "чтобы продолжить в Круге Глифов",
  "selectAccount": "Выберите аккаунт",
  "useAnotherAccount": "Использовать другой аккаунт",
  "enterOTP": "Введите OTP",
  "otpPrompt": "6-значный код был отправлен на ваш телефон.",
  "otpDemo": "Для демонстрации используйте OTP: 123456",
  "verify": "Проверить",
  "back": "Назад",
  "unlockReport": "Разблокировать полный отчет",
  "paymentPrompt": "За единовременную плату в {price} получите полный доступ к вашему подробному чтению.",
  "billingInfo": "Платежная информация",
  "address": "Адрес",
  "city": "Город",
  "zip": "Почтовый индекс",
  "country": "Страна",
  "proceedToPayment": "Перейти к оплате",
  "payTo": "Вы платите:",
  "creditCard": "Кредитная или дебетовая карта",
  "paypal": "PayPal",
  "paypalNote": "Платежи будут отправлены на {email}",
  "payNow": "Оплатить сейчас",
  "paymentSuccessTitle": "Оплата прошла успешно!",
  "paymentSuccessMsg": "Ваш полный отчет теперь разблокирован.",
  "adminDashboard": "Панель администратора",
  "runTheApp": "Запустить приложение",
  "runTheAppDesc": "Перейти к основному приложению для пользователей.",
  "showTheConfig": "Показать конфигурацию",
  "showTheConfigDesc": "Доступ к панели администратора для управления приложением.",
  "adminConfigTitle": "Конфигурация администратора",
  "adminConfigDesc": "Выберите таблицу базы данных для просмотра и управления ее записями. Внесенные здесь изменения сохраняются на время сеанса вашего браузера.",
  "editing": "Редактирование: {tableName}",
  "toggleStatus": "Переключить статус",
  "createNewEntry": "Создать новую запись",
  "actions": "Действия",
  "noEntries": "В этой таблице нет записей.",
  "createEntryIn": "Создать новую запись в {tableName}",
  "cancel": "Отмена",
  "create": "Создать",
  "featureComingSoon": "{featureName} скоро появится.",
  "stayTuned": "Следите за мистическими прозрениями!",
  "goBackHome": "Вернуться на главную"
};

const ja = {
  "logout": "ログアウト",
  "welcomeToPath": "発見の道へようこそ",
  "chooseService": "下のサービスを選択して、神秘的な芸術への旅を始め、内なる知恵を解き放ちましょう。",
  "numerology": "数秘術",
  "numerologyDesc": "あなたの名前と生年月日に隠された秘密を明らかにします。",
  "astrology": "占星術",
  "astrologyDesc": "星や惑星に書かれたあなたの運命を探ります。",
  "tarot": "タロット",
  "tarotDesc": "カードを引いて、あなたの過去、現在、未来への洞察を得ます。",
  "palmistry": "手相",
  "palmistryDesc": "あなたの手の線を読んで、あなたの性格と未来を理解します。",
  "faceReading": "顔相",
  "faceReadingDesc": "あなたの顔の特徴があなたの性格について何を明らかにしているかを発見します。",
  "personalGuidance": "パーソナルガイダンス",
  "personalGuidanceDesc": "あなたの人生の課題に対する個別の救済策とガイダンスを得ます。",
  "backToHome": "ホームに戻る",
  "backToDashboard": "ダッシュボードに戻る",
  "aiPalmReading": "AI手相占い",
  "uploadPalmPrompt": "手のひらの鮮明な写真をアップロードして、即座にAIによる手相占いを受け取ります。",
  "uploadInstruction": "クリックして写真をアップロードまたは撮影します",
  "getYourReading": "私の占い結果を見る",
  "analyzing": "分析中...",
  "yourReading": "あなたの占い結果:",
  "readingPlaceholder": "あなたの手相占いの要約がここに表示されます。",
  "readMore": "続きを読む（支払いが必要です）",
  "downloadPDF": "PDFをダウンロード",
  "emailReport": "レポートをメールで送信",
  "paymentSuccessful": "支払いが成功しました！完全なレポートにアクセスしてください。",
  "aiFaceReading": "AI顔相占い",
  "uploadFacePrompt": "顔の鮮明な写真をアップロードして、即座にAIによる顔相占いを受け取ります。",
  "faceReadingPlaceholder": "あなたの顔相占いの要約がここに表示されます。",
  "numerologyReading": "数秘術占い",
  "astrologyReading": "占星術占い",
  "enterDetailsPrompt": "以下に詳細を入力して、パーソナライズされた{featureName}の要約を生成します。",
  "fullName": "氏名",
  "dob": "生年月日",
  "pob": "出生地",
  "tob": "出生時間",
  "pobOptional": "出生地（数秘術ではオプション）",
  "tobOptional": "出生時間（数秘術ではオプション）",
  "getMy": "私の{featureName}占い結果を見る",
  "generating": "生成中...",
  "yourSummary": "あなたの{featureName}の要約",
  "tarotReading": "タロット占い",
  "tarotPrompt": "大アルカナからカードを1枚選んで、あなたにとっての神秘的な意味を明らかにします。",
  "glyphCircle": "グリフサークル",
  "enterCircle": "知恵の輪に入ります。",
  "username": "ユーザー名",
  "password": "パスワード",
  "login": "ログイン",
  "orContinueWith": "または続ける",
  "signInGoogle": "Googleでサインイン",
  "signInPhone": "電話番号でサインイン",
  "noAccount": "アカウントをお持ちではありませんか？",
  "createOne": "作成する",
  "createAccount": "アカウントを作成",
  "email": "メールアドレス",
  "confirmPassword": "パスワードの確認",
  "backToLogin": "ログインに戻る",
  "signIn": "サインイン",
  "toContinue": "グリフサークルを続けるには",
  "selectAccount": "アカウントを選択",
  "useAnotherAccount": "別のアカウントを使用",
  "enterOTP": "OTPを入力",
  "otpPrompt": "6桁のコードがあなたの電話に送信されました。",
  "otpDemo": "デモ用には、OTP：123456を使用してください",
  "verify": "確認",
  "back": "戻る",
  "unlockReport": "完全なレポートをアンロック",
  "paymentPrompt": "{price}の一回払いで、詳細な占い結果への完全なアクセス権を得ます。",
  "billingInfo": "請求情報",
  "address": "住所",
  "city": "市",
  "zip": "郵便番号",
  "country": "国",
  "proceedToPayment": "支払いに進む",
  "payTo": "支払先：",
  "creditCard": "クレジットカードまたはデビットカード",
  "paypal": "PayPal",
  "paypalNote": "支払いは{email}に送信されます",
  "payNow": "今すぐ支払う",
  "paymentSuccessTitle": "支払いが成功しました！",
  "paymentSuccessMsg": "あなたの完全なレポートがアンロックされました。",
  "adminDashboard": "管理ダッシュボード",
  "runTheApp": "アプリを実行",
  "runTheAppDesc": "メインのユーザー向けアプリケーションに進みます。",
  "showTheConfig": "設定を表示",
  "showTheConfigDesc": "アプリケーションを管理するための管理パネルにアクセスします。",
  "adminConfigTitle": "管理設定",
  "adminConfigDesc": "データベーステーブルを選択して、そのエントリを表示および管理します。ここで行われた変更は、ブラウザセッション用に保存されます。",
  "editing": "編集中：{tableName}",
  "toggleStatus": "ステータスを切り替える",
  "createNewEntry": "新しいエントリを作成",
  "actions": "アクション",
  "noEntries": "このテーブルにはエントリがありません。",
  "createEntryIn": "{tableName}に新しいエントリを作成",
  "cancel": "キャンセル",
  "create": "作成",
  "featureComingSoon": "{featureName}は近日公開予定です。",
  "stayTuned": "神秘的な洞察をお楽しみに！",
  "goBackHome": "ホームに戻る"
};

const zh = {
  "logout": "登出",
  "welcomeToPath": "欢迎来到您的发现之路",
  "chooseService": "选择下面的服务，开始您的神秘艺术之旅，解锁内在的智慧。",
  "numerology": "命理学",
  "numerologyDesc": "揭开隐藏在您姓名和出生日期中的秘密。",
  "astrology": "占星术",
  "astrologyDesc": "探索写在星辰和行星中的您的命运。",
  "tarot": "塔罗牌",
  "tarotDesc": "抽一张牌，洞察您的过去、现在和未来。",
  "palmistry": "手相",
  "palmistryDesc": "解读您手上的线条，了解您的性格和未来。",
  "faceReading": "面相",
  "faceReadingDesc": "发现您的面部特征揭示了您的个性。",
  "personalGuidance": "个人指导",
  "personalGuidanceDesc": "为您的生活挑战获得个性化的补救措施和指导。",
  "backToHome": "返回首页",
  "backToDashboard": "返回仪表板",
  "aiPalmReading": "AI手相解读",
  "uploadPalmPrompt": "上传一张清晰的手掌照片，即可获得即时的人工智能手相解读。",
  "uploadInstruction": "点击上传或拍摄照片",
  "getYourReading": "获取我的解读",
  "analyzing": "分析中...",
  "yourReading": "您的解读：",
  "readingPlaceholder": "您的手相解读摘要将显示在此处。",
  "readMore": "阅读更多（需要付费）",
  "downloadPDF": "下载PDF",
  "emailReport": "通过电子邮件发送报告",
  "paymentSuccessful": "支付成功！访问您的完整报告。",
  "aiFaceReading": "AI面相解读",
  "uploadFacePrompt": "上传一张清晰的脸部照片，即可获得即时的人工智能面相解读。",
  "faceReadingPlaceholder": "您的面相解读摘要将显示在此处。",
  "numerologyReading": "命理学解读",
  "astrologyReading": "占星术解读",
  "enterDetailsPrompt": "在下方输入您的详细信息，以生成您的个性化{featureName}摘要。",
  "fullName": "全名",
  "dob": "出生日期",
  "pob": "出生地",
  "tob": "出生时间",
  "pobOptional": "出生地（命理学可选）",
  "tobOptional": "出生时间（命理学可选）",
  "getMy": "获取我的{featureName}解读",
  "generating": "生成中...",
  "yourSummary": "您的{featureName}摘要",
  "tarotReading": "塔罗牌解读",
  "tarotPrompt": "从大阿尔克那中选择一张牌，揭示它对您的神秘意义。",
  "glyphCircle": "符文圈",
  "enterCircle": "进入智慧的圈子。",
  "username": "用户名",
  "password": "密码",
  "login": "登录",
  "orContinueWith": "或继续使用",
  "signInGoogle": "使用Google登录",
  "signInPhone": "使用电话号码登录",
  "noAccount": "没有账户？",
  "createOne": "创建一个",
  "createAccount": "创建您的账户",
  "email": "电子邮件",
  "confirmPassword": "确认密码",
  "backToLogin": "返回登录",
  "signIn": "登录",
  "toContinue": "以继续访问符文圈",
  "selectAccount": "选择一个账户",
  "useAnotherAccount": "使用另一个账户",
  "enterOTP": "输入OTP",
  "otpPrompt": "一个6位数的代码已发送到您的手机。",
  "otpDemo": "演示请使用OTP：123456",
  "verify": "验证",
  "back": "返回",
  "unlockReport": "解锁完整报告",
  "paymentPrompt": "一次性支付{price}，即可完全访问您的详细解读。",
  "billingInfo": "账单信息",
  "address": "地址",
  "city": "城市",
  "zip": "邮政编码",
  "country": "国家",
  "proceedToPayment": "继续支付",
  "payTo": "您正在支付给：",
  "creditCard": "信用卡或借记卡",
  "paypal": "PayPal",
  "paypalNote": "付款将发送至{email}",
  "payNow": "立即支付",
  "paymentSuccessTitle": "支付成功！",
  "paymentSuccessMsg": "您的完整报告现已解锁。",
  "adminDashboard": "管理仪表板",
  "runTheApp": "运行应用程序",
  "runTheAppDesc": "进入面向用户的主应用程序。",
  "showTheConfig": "显示配置",
  "showTheConfigDesc": "访问管理面板以管理应用程序。",
  "adminConfigTitle": "管理配置",
  "adminConfigDesc": "选择一个数据库表以查看和管理其条目。此处所做的更改将为您当前的浏览器会话保存。",
  "editing": "正在编辑：{tableName}",
  "toggleStatus": "切换状态",
  "createNewEntry": "创建新条目",
  "actions": "操作",
  "noEntries": "此表中没有条目。",
  "createEntryIn": "在{tableName}中创建新条目",
  "cancel": "取消",
  "create": "创建",
  "featureComingSoon": "{featureName} 即将推出。",
  "stayTuned": "敬请期待神秘的见解！",
  "goBackHome": "返回首页"
};

type Language = 'en' | 'hi' | 'fr' | 'es' | 'de' | 'ru' | 'ja' | 'zh';
type Translations = Record<string, any>;

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  translations: Translations;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const languages: Record<Language, Translations> = { en, hi, fr, es, de, ru, ja, zh };

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const setLanguageCallback = useCallback((lang: Language) => {
    setLanguage(lang);
  }, []);

  return (
    <LanguageContext.Provider value={{ language, setLanguage: setLanguageCallback, translations: languages[language] }}>
      {children}
    </LanguageContext.Provider>
  );
};